---
# tasks file for cpanel

    - name: "Installing System Updates"
      yum:
        name: "*"
        state: latest

    - name: "Install Required Packages"
      yum:
        name:
          - perl
          - curl
        state: latest
    - name: "Change hostname"
      ansible.builtin.hostname:
        name: example.cpanel.com

    - name: "Download cPanel"
      shell: curl -o latest -L https://securedownloads.cpanel.net/latest

    - name: "Correct Permissions"
      shell: chmod +x latest

    - name: "Install cPanel"
      shell: sh latest
